name: lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Lint script
        uses: azohra/shell-linter@v0.5.0
        with:
          path: wgmon.sh
